name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment for deployment'
        required: true
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.7.5"

    - name: Initialize Terraform
      run: terraform init
      working-directory: ./terraform/${{ github.event.inputs.environment }}

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform/${{ github.event.inputs.environment }}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform/${{ github.event.inputs.environment }}
      env:
        TF_VAR_selected_environment: ${{ github.event.inputs.environment }}
