name: Deploy Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.7.5"
      
      - name: Terraform Init
        run: terraform init
        env:
          TF_VAR_HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -out=tfplan
          terraform show -no-color tfplan > plan.txt
        continue-on-error: true

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan
          path: tfplan

  terraform_apply:
    needs: terraform_plan
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.7.5"
      
      - name: Terraform Init
        run: terraform init
        env:
            TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}

      - name: Download Terraform Plan
        uses: actions/download-artifact@v2
        with:
          name: terraform-plan
          path: .

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
