name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment for deployment'
        required: true
        type: choice
        options:
          - staging
          - production

jobs:
  terraform_plan:
    uses: ./.github/workflows/terraform-plan.yml
    secrets: inherit

  terraform_apply:
    needs: terraform_plan
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: ${{ inputs.environment }}
    secrets:
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}