name: Deploy

on:
  workflow_dispatch:

jobs:
  terraform_plan:
    uses: ./.github/workflows/terraform-plan.yml@main

  terraform_apply:
    needs: terraform_plan
    uses: ./.github/workflows/terraform-apply.yml@main
    with:
      environment: ${{ inputs.environment }}