name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        type: choice
        description: 'Target environment for deployment'
        options:
        - production
        - staging
        

  workflow_dispatch:

jobs:
  terraform_plan:
    uses: ./.github/workflows/terraform-plan.yml@main

  terraform_apply:
    needs: terraform_plan
    uses: ./.github/workflows/terraform-apply.yml@main
    with:
      environment: ${{ inputs.environment }}