name: Terraform Plan

on:
  workflow_call:

  workflow_dispatch:

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    env:
      TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ${{ github.workspace }}/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ${{ github.workspace }}/.ssh/id_rsa
          chmod 600 ${{ github.workspace }}/.ssh/id_rsa

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"

      - name: Terraform Init
        run: terraform init
        env:
          TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
        working-directory: ./terraform

      - name: Terraform Plan
        run: |
          terraform plan -input=false -var="ssh_private_key_path=${{ github.workspace }}/.ssh/id_rsa" -out=tfplan
        env:
          TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
        working-directory: ./terraform

