name: Terraform Apply

on:
  workflow_call:
    inputs:
      environment:
        description: 'Target environment for deployment'
        required: true
        type: string
      hcloud_token:
        required: true
        description: Hetzner Cloud API Token
        type: secret

  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment for deployment'
        required: true
        type: string
      hcloud_token:
        required: true
        description: Hetzner Cloud API Token
        type: secret

jobs:
  terraform_apply:
    environment: ${{ inputs.environment}}
    runs-on: ubuntu-latest
    env:
      TF_VAR_hcloud_token: ${{ inputs.hcloud_token }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ${{ github.workspace }}/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ${{ github.workspace }}/.ssh/id_rsa
          chmod 600 ${{ github.workspace }}/.ssh/id_rsa

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"
      
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -input=false -var="ssh_private_key_path=${{ github.workspace }}/.ssh/id_rsa" -auto-approve
        working-directory: ./terraform